apiVersion: v1
data:
    password: ENC[AES256_GCM,data:m0PmUGEXKuw=,iv:XHCXqD9xh2NHR3/kqNUJ/IYiUDl74ALrSFBCxpY26as=,tag:RjiFKIuNr11wi4PefoOIcQ==,type:str]
    user: ENC[AES256_GCM,data:+gw/Pe+0gxw=,iv:RLTene1OaQUQHwt+8kBDrmV+PR9xW/BnP8zPpeVFLK0=,tag:LDwX+1xyGbF01Ag04ZfVzg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1ajtgd949uyxprw7zrh8yxvz7r0lgn9m57u6k662h67cuwv8kuy3spwv4rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U0JwbGNoODI0RXZUL2Zi
            NFdSMUFYSlRnd0N2aTB2QXpQK0pteVA0UlFjCjE1SlJONURwVXdtMTMrWSsvZERq
            OHRyR05BbzJzcnVMY2dGNTZHN0tYR28KLS0tIFVlUFoxRHltcklzeWxCdDVCaFUw
            dUc3cjdrTmhndTFTTDBXeFFlck4rVUEKWf3x+cuJZUS5CIFltMveDWCxtEu9njhG
            SpK/+EDNppk44kPKQijtGjcAWO2nXoigUBEBN5KAIubub7XLUkNAYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T15:22:23Z"
    mac: ENC[AES256_GCM,data:wD/GctdXx3V6FySBi2J/b9qRfvvNLwQjj93/kgMk8pq9eYLbAcF7QeKC3ah1xGMbwkQweqU0nZHM/JvwzMyfMLZMe+QJENTYmrD5aXePIUq9AYKuePvw87UfEF2d6wzm7TQe3UohcQllcbYlz3kbu91eYSPY1HWy49Qcw+KYEN0=,iv:STuT1i1VqWUpEy+SpYT/UC2TKXt2FqcUayOIk/jrNag=,tag:1nNB/F58d7JygsQdit0YLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
